### ISSUE TITLE
this.$segment is undefined

### ISSUE THREAD

**Issue by indrakusumax** [guivic/vue-segment#2]
This is my dependencies:
"dependencies": {
    "@guivic/vue-segment": "0.0.1",
    "axios": "^0.18.0",
    "lodash": "^4.17.5",
    "marked": "^0.3.16",
    "q": "^1.5.1",
    "vue": "^2.5.11",
    "vue-easy-slider": "^3.2.0",
    "vue-headful": "^1.0.0",
    "vue-js-modal": "^1.3.12",
    "vue-moment": "^3.2.0",
    "vue-router": "^3.0.1",
    "vue-simple-spinner": "^1.2.8",
    "vuex": "^3.0.1"
  }

Already did the initialization as well:
import VueSegment from '@guivic/vue-segment';
Vue.use(VueSegment, { writeKey: 'some_key' });

and then try to use it on component.
       console.log(this.$segment);
        this.$segment.track({
          event: 'click on gallery image',
          name: image.title
        });
I got this.$segment undefined.

![gambar](https://user-images.githubusercontent.com/618443/37941590-880ebc5e-31a1-11e8-8dc4-0071a2f624bf.png)

**Comment by guillaume-g** [comment]
Hey

I just fixed the bug, I assigned to Vue and forgot to do it for Vue.prototype...
Please upgrade to 0.0.2, do not hesitate to tell me if anything else goes wrong.

Thanks for using @guivic/vue-segment ! I hope you will continue to use our open-source projects :)
